version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11

    commands:
    - echo Install Start
    - yum install -y wget unzip
    - export VER="0.12.1"
    - wget https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.zip
    - unzip terraform_${VER}_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - echo $aws_access_key_id
    - echo $aws_secret_access_key
    - cat prod/main.tf
#   - aws s3 cp s3://test-ray-credential/ . --recursive
  build:
    commands:
    - echo Build started on 'date'
    - cd prod
    - ls -al main.tf
#   - cp -a ../terraform_state/terraform.tfstate .
    - sed -i "s|my_access_key|\"$aws_access_key_id\"|g" main.tf
    - sed -i "s|my_secret_key|\"$aws_secret_access_key\"|g" main.tf 
    - cat main.tf
    - terraform init
    - terraform plan
    - terraform apply -auto-approve
#   - aws s3 cp terraform.tfstate s3://test-ray-credential/terraform_state/
  post_build:
    commands:
    - echo build compeleted on 'date'
#artifacts:
#   files:
#    - '**/*'
#   name: arti-$(date+%Y-%m-%d)
